blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('haystack.urls')),
    url(r'^', include('post.urls', namespace='post')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.post_list, name='post_list_by_category'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post_slug>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/(?P<post_id>\d+)/pdf/$', views.post_pdf, name='post_pdf'),
]

post/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager

class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, db_index=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('post:post_list_by_category', args=[self.slug])

class Post(models.Model):
    POST_STATUS = (
        ('PUBLISHED', 'Published'),
        ('DRAFT', 'Draft')
    )
    category = models.ForeignKey(Category, related_name='posts')
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique_for_date='publish')
    tags = TaggableManager()
    content = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=POST_STATUS)

    class Meta:
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:post_detail', args=[self.publish.year, self.publish.strftime('%m'),
                        self.publish.strftime('%d'), self.slug])

    def get_published():
        return Post.objects.filter(status="PUBLISHED")

post/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.http import HttpResponse
from django.template.loader import render_to_string
import weasyprint

def post_list(request, category_slug=None, tag_slug=None):
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        tag = None
        posts = Post.get_published().filter(category=category)
    elif tag_slug:
        category = None
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = Post.get_published().filter(tags__in=[tag])
    else:
        category = None
        tag = None
        posts = Post.get_published()
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    categories = Category.objects.all()
    return render(request, 'post/list.html', {'category': category, 'categories': categories, 'posts': posts, 'tag': tag})

def post_detail(request, year, month, day, post_slug):
    post = get_object_or_404(Post.get_published(), publish__year=year, publish__month=month, publish__day=day, slug=post_slug)
    categories = Category.objects.all()
    return render(request, 'post/detail.html', {'categories': categories, 'post': post})

def post_pdf(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    html = render_to_string('post/post_pdf.html', {'post': post})                 
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=\"post_{}.pdf"'.format(post_id)
    weasyprint.HTML(string=html).write_pdf(response)
    return response

post/templates/base.html
{% load post_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}大兔崽子的博客{% endblock %}</title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="./homepage.css">  
    <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img width="20px" height="20px" alt="Brand" src="{% static "img/brand.jpg" %}" class="img-circle">
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'post:post_list' %}">全部</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">分类<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">类别</li>
                            {% for c in categories %}
                            <li>
                                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-right" method="get" action="{% url "haystack_search" %}">
                    <div class="form-group">
                        <input type="search" class="form-control" placeholder="关键字" name="q">
                    </div>
                    <button type="submit" class="btn btn-default" value="Search">搜索</button>
                </form>
            </div>
        </div>
    </nav>
    <a name="top"></a>
    <span class="blank" style="height:60px;"></span>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                {% block content %} {% endblock %}
            </div>
            <div class="col-md-3">
                <div class="row">
                    <div class="col-md-10">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h3 class="panel-title text-center">大兔崽子的博客</h3>
                            </div>
                            <div class="panel-body">
                                使用Django和Bootstrap构建的个人博客
                            </div>
                            <ul class="list-group">
                                <li class="list-group-item">
                                    {% if category %}
                                        {{ category }}主题共写了 {% total_posts category %} 篇文章
                                    {% elif post %}
                                        {{ post.category }}主题共写了 {% total_posts post.category %} 篇文章
                                    {% else %}
                                        共写了 {% total_posts post.category %} 篇文章
                                    {% endif %}
                                </li>
                                <li class="list-group-item">
                                    最新文章
                                    {% latest_posts %}
                                </li>
                                {% if post %}
                                <li class="list-group-item">
                                    相关文章 
                                    {% similar_posts post %}
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>  
                <div class="btn-group-vertical" role="group" aria-label="..." style="position:fixed; right:150px; bottom:20px;">
                        <button type="button" class="btn btn-default"><a href="#top">回到顶部</a></button>
                        <button type="button" class="btn btn-default">
                            <!-- JiaThis Button BEGIN -->
                            <div id="ckepop">
                                <span class="jiathis_txt">分享到：</span>
                                <a class="jiathis_button_weixin">微信</a> 
                                <br/>
                                <a href="http://www.jiathis.com/share"  class="jiathis jiathis_txt jiathis_separator jtico jtico_jiathis" target="_blank">更多</a>
                                <a class="jiathis_counter_style"></a>
                                <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1" charset="utf-8"></script>   
                            </div> 
                            <!-- JiaThis Button END -->
                        </button>
                        {% if post %}
                        <button type="button" class="btn btn-default"><a href="{% url "post:post_pdf" post.id %}">将文章<br/>导出为PDF</a></button>
                        {% endif %}
                </div>   
            </div>
        </div>
    </div>  
</body>

</html>

post/templates/post/detail.html
{% extends "base.html" %}
{% load post_tags %}
{% load static %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="row content">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <h1 class="h1">{{ post.title }}</h1>
            <h3 class="h3">
                <small>{{ post.publish }}</small>
                <small>
                    <a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a>
                </small>
            </h3>
            <small>
                <strong>标签 </strong>
                {% for post_tag in post.tags.all %}
                    <a href="{% url "post:post_list_by_tag" post_tag.slug %}"><span class="badge">{{ post_tag.name }}</span></a>
                {% endfor %}
            </small>
            <p>{{ post.content|markdown }}</p>
        </div>
        <div class="col-md-1"></div>
    </div>
{% endblock %}

post/templates/post/latest_posts.html
<ul class="list-group">
    {% for post in posts %}
    <li class="list-group-item">
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

post/templates/post/list.html
{% extends "base.html" %} 
{% load post_tags %} 
{% load static %} 

{% block title %} 
    大兔崽子的博客{% if category %}-{{ category.name }}{% else %}{% endif %} 
{% endblock %} 

{% block content %}
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <h1 class="h1">
                {% if category %}
                    {{ category.name }}
                {% elif tag %}
                    {{ tag.name }}
                {% else %}
                    文章列表
                {% endif %}
            </h1>
        </div>
        <div class="col-md-1"></div>
    </div>
    {% for post in posts %}
    <div class="row content">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <h3>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                <small>{{ post.publish }}</small>
            </h3>
            <small>
                <strong>标签 </strong>
                {% for post_tag in post.tags.all %}
                    <a href="{% url "post:post_list_by_tag" post_tag.slug %}"><span class="badge">{{ post_tag.name }}</span></a>
                {% endfor %}
            </small>
            <p>
                {{ post.content|markdown|truncatewords_html:30}}
            </p>
        </div>
        <div class="col-md-1"></div>
    </div>
    {% endfor %}
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <nav aria-label="Page navigation">
                <ul class="pager">
                    {% if posts.has_previous %}
                        <li class="previous"><a href="?page={{ posts.previous_page_number }}">前一页</a></li> 
                    {% else %}
                        <li class="previous disabled"><a href="#">前一页</a></li>
                    {% endif %}
                    Page <span class="badge">{{ posts.number }}</span> of <span class="badge">{{ posts.paginator.num_pages }}</span> 
                    {% if posts.has_next %}
                        <li class="next"><a href="?page={{ posts.next_page_number }}">后一页</a></li> 
                    {% else %}
                        <li class="next disabled"><a href="#">后一页</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <div class="col-md-1"></div>
    </div>
{% endblock %}

post/templates/post/post_pdf.html
{% load post_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="./homepage.css">
    <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>
    <h1 class="h1">{{ post.title }}</h1>
    <h3 class="h3">
        <small>{{ post.publish }}</small>
        <small>
            <a href="127.0.0.1:8000{{ post.get_absolute_url }}">原文链接</a>
        </small>
    </h3>
    <small>
        <strong>标签 </strong>
        {% for post_tag in post.tags.all %}
            <span class="badge">{{ post_tag.name }}</span>
        {% endfor %}
    </small>
    <p>{{ post.content|markdown }}</p>
</body>
</html>

post/templates/post/similar_posts.html
<ul class="list-group">
    {% for post in similar_posts %}
    <li class="list-group-item">
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

post/templates/search/search.html
{% extends 'base.html' %}

{% block content %}
<!--
    <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td> </td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>
    </form>
-->
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <h1 class="h1">
                搜索结果
            </h1>
        </div>
        <div class="col-md-1"></div>
    </div>

    {% for result in page.object_list %}
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <p>
                <a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>
            </p>
        </div>
        <div class="col-md-1"></div>
    </div>
    {% empty %}
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <p>
                没有相关文章
            </p>
        </div>
        <div class="col-md-1"></div>
    </div>
    {% endfor %} 
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <nav aria-label="Page navigation">
                <ul class="pager">
                    {% if page.has_previous %}
                        <li class="previous"><a href="?q={{ query }}&page={{ page.previous_page_number }}">前一页</a></li>
                    {% else %}
                        <li class="previous disabled"><a href="#">前一页</a></li>
                    {% endif %} 
                    Page <span class="badge">{{ page.number }}</span> of <span class="badge">{{ page.paginator.num_pages }}</span>                    
                    {% if page.has_next %}
                        <li class="next"><a href="?q={{ query }}&page={{ page.next_page_number }}">后一页</a></li>
                    {% else %}
                        <li class="next disabled"><a href="#">后一页</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <div class="col-md-1"></div>
    </div>
{% endblock %}